import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedPatternsLabeledDark4itemsWidget8.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedMobileTopBarDarkWidget8.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedFrame19Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedMobileTopBarDarkWidget9.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedSurfaceWidget8.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedPatternsLabeledDark4itemsWidget9.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedFrame18Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedFrame18Widget2.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedFrame20Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget1/generated/GeneratedFrame3Widget.dart';

/* Frame History
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedPatternsLabeledDark4itemsWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 77.0,
                child: GeneratedMobileTopBarDarkWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedPatternsLabeledDark4itemsWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 77.0,
                child: GeneratedMobileTopBarDarkWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFrame18Widget1(),
              ),
              Positioned(
                left: 0.0,
                top: 111.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFrame18Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 136.0,
                height: 42.0,
                child: GeneratedFrame19Widget1(),
              ),
              Positioned(
                left: 100.0,
                top: 154.0,
                right: null,
                bottom: null,
                width: 75.0,
                height: 25.0,
                child: GeneratedSurfaceWidget8(),
              ),
              Positioned(
                left: 169.0,
                top: 146.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 42.0,
                child: GeneratedFrame20Widget1(),
              ),
              Positioned(
                left: 5.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 123.0,
                child: GeneratedFrame3Widget(),
              )
            ]),
      ),
    ));
  }
}
