import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstartseitewidget/generated/GeneratedLabel_TitelWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstartseitewidget/generated/GeneratedRectangle_TitelWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstartseitewidget/generated/GeneratedStartseite_Button_LoginWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstartseitewidget/generated/GeneratedStartseite_Button_RegistrierungWidget.dart';

/* Frame Startseite
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStartseiteWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
            child: Container(
              width: 360.0,
              height: 640.0,
                child: Stack(
                  clipBehavior: Clip.none, fit: StackFit.expand,
                  alignment: Alignment.center,
                  children: [
                       ClipRRect(
                            borderRadius: BorderRadius.zero,
                         child: Container(
                             color: Color.fromARGB(255, 58, 159, 165),
                              ),
                            ),
                        Positioned(
                          left: 71.0,
                          top: 88.0,
                          right: null,
                          bottom: null,
                          width: 225.0,
                          height: 225.0,
                                       child: GeneratedRectangle_TitelWidget(),
              ),
              Positioned(
                left: 68.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 167.0,
                child: GeneratedLabel_TitelWidget(),
              ),
              Positioned(
                left: 111.0,
                top: 371.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 40.0,
                child: GeneratedStartseite_Button_LoginWidget(),
              ),
              Positioned(
                left: 111.0,
                top: 437.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 40.0,
                child: GeneratedStartseite_Button_RegistrierungWidget(),
              )
            ]),
      ),
    ));
  }
}
