import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedAbfahrtWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedFrame27Widget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedFirmennameZielWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedPWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedStandEndeWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedStartHausnrWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedZielStraeWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedPatternsLabeledDark4itemsWidget5.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedStartadresseWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedZielPLZWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedStandBeginnWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedLabel_KilometerstandWidget2.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedAnkunftWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedZielOrtWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedFavoriten_Frame_ExportStartWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedStartStraeWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedFahrt_Text_StartHausnrWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedZweckWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedMobileTopBarDarkWidget5.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedFavoriten_Frame_ExportZielWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedIconicRightAccentWidget3.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedPrivatWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedFirmennameStartWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedStartOrtWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedDatumWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedneuefahrtwidget/generated/GeneratedStartPLZWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedRegistrierung_Text_KennzeichenWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedregistrierungwidget/generated/GeneratedRegistrierung_Text_PLZWidget1.dart';

import 'generated/GeneratedZielHausnrWidget.dart';


/* Frame Neue Fahrt
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNeueFahrtWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {

    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            clipBehavior: Clip.none, fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 77.0,
                child: GeneratedMobileTopBarDarkWidget5(),
              ),
              Positioned(
                left: 2.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedDatumWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 149.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFirmennameStartWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 133.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 20.0,
                child: GeneratedStartadresseWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 94.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedAbfahrtWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 341.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 40.0,
                child: GeneratedAnkunftWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 448.0,
                right: null,
                bottom: null,
                width: 317.0,
                height: 31.0,
                child: GeneratedLabel_KilometerstandWidget2(),
              ),
              Positioned(
                left: 0.0,
                top: 468.0,
                right: null,
                bottom: null,
                width: 206.0,
                height: 42.0,
                child: GeneratedStandBeginnWidget(),
              ),
              Positioned(
                left: 203.0,
                top: 469.0,
                right: null,
                bottom: null,
                width: 148.0,
                height: 39.0,
                child: GeneratedStandEndeWidget(),
              ),
              Positioned(
                left: 1.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 351.0,
                height: 84.0,
                child: GeneratedZweckWidget(),
              ),
              Positioned(
                left: 4.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedStartStraeWidget(),
              ),
              Positioned(
                left: 126.0,
                top: 177.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedStartHausnrWidget(),
              ),
              Positioned(
                left: 5.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 169.0,
                height: 42.0,
                child: GeneratedStartPLZWidget(),
              ),
              Positioned(
                left: 170.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 179.0,
                height: 42.0,
                child: GeneratedStartOrtWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedZielStraeWidget(),
              ),
              Positioned(
                left: 126.0,
                top: 286.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedZielHausnrWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 258.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFirmennameZielWidget(),
              ),
              Positioned(
                left: 230.0,
                top: 241.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 20.0,
                child: GeneratedFavoriten_Frame_ExportZielWidget(),
              ),
              Positioned(
                left: 2.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 175.0,
                height: 42.0,
                child: GeneratedZielPLZWidget(),
              ),
              Positioned(
                left: 171.0,
                top: 313.0,
                right: null,
                bottom: null,
                width: 176.0,
                height: 42.0,
                child: GeneratedZielOrtWidget(),
              ),
              Positioned(
                left: -1.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedPatternsLabeledDark4itemsWidget5(),
              ),
              Positioned(
                left: 14.0,
                top: 518.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 48.0,
                child: GeneratedIconicRightAccentWidget3(),
              ),
              Positioned(
                left: 217.0,
                top: 85.0,
                right: null,
                bottom: null,
                width: 155.0,
                height: 52.0,
                child: GeneratedPrivatWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 240.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 20.0,
                child: GeneratedFrame27Widget(),
              ),
              Positioned(
                left: 230.0,
                top: 132.0,
                right: null,
                bottom: null,
                width: 160.0,
                height: 20.0,
                child: GeneratedFavoriten_Frame_ExportStartWidget(),
              )
            ]),
      ),
    ));
  }
}
