import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget/generated/GeneratedMobileTopBarDarkWidget7.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget/generated/GeneratedPatternsLabeledDark4itemsWidget6.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget/generated/GeneratedMobileTopBarDarkWidget6.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget/generated/GeneratedPatternsLabeledDark4itemsWidget7.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedhistorywidget/generated/GeneratedFrame2Widget1.dart';

/* Frame History
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedPatternsLabeledDark4itemsWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 77.0,
                child: GeneratedMobileTopBarDarkWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedPatternsLabeledDark4itemsWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 77.0,
                child: GeneratedMobileTopBarDarkWidget7(),
              ),
              Positioned(
                left: 7.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 347.0,
                height: 150.0,
                child: GeneratedFrame2Widget1(),
              )
            ]),
      ),
    ));
  }
}
