import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstatistikwidget1/generated/GeneratedDefaultWidget3.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstatistikwidget1/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstatistikwidget1/generated/GeneratedMobileTopBarDarkWidget10.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstatistikwidget1/generated/GeneratedPatternsLabeledDark4itemsWidget10.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstatistikwidget1/generated/GeneratedDefaultWidget2.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedstatistikwidget1/generated/GeneratedLightPieChartWidget1.dart';

/* Frame Statistik
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedStatistikWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 362.0,
                height: 77.0,
                child: GeneratedMobileTopBarDarkWidget10(),
              ),
              Positioned(
                left: 6.0,
                top: 103.0,
                right: null,
                bottom: null,
                width: 345.0,
                height: 43.0,
                child: GeneratedFrame1Widget1(),
              ),
              Positioned(
                left: 195.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 58.0,
                child: GeneratedDefaultWidget2(),
              ),
              Positioned(
                left: 25.0,
                top: 186.0,
                right: null,
                bottom: null,
                width: 144.0,
                height: 58.0,
                child: GeneratedDefaultWidget3(),
              ),
              Positioned(
                left: 11.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 340.0,
                height: 269.0,
                child: GeneratedLightPieChartWidget1(),
              ),
              Positioned(
                left: 1.0,
                top: 576.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedPatternsLabeledDark4itemsWidget10(),
              )
            ]),
      ),
    ));
  }
}
