import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedprofilwidget/generated/GeneratedFahrzeugdatenWidget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedprofilwidget/generated/GeneratedEMailWidget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedprofilwidget/generated/GeneratedFirmendatenWidget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedprofilwidget/generated/GeneratedProfilWidget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedprofilwidget/generated/GeneratedSingleButtonWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedprofilwidget/generated/GeneratedPersonendatenWidget1.dart';

/* Frame Profil
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfilWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 17.0,
                right: null,
                bottom: null,
                width: 365.0,
                height: 42.0,
                child: GeneratedProfilWidget1(),
              ),
              Positioned(
                left: -2.0,
                top: 552.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 64.0,
                child: GeneratedSingleButtonWidget(),
              ),
              Positioned(
                left: 14.0,
                top: 136.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 184.0,
                child: GeneratedPersonendatenWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 37.0,
                child: GeneratedEMailWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 409.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 131.0,
                child: GeneratedFahrzeugdatenWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 312.0,
                right: null,
                bottom: null,
                width: 333.0,
                height: 113.0,
                child: GeneratedFirmendatenWidget1(),
              )
            ]),
      ),
    ));
  }
}
