import 'package:flutter/material.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedloginwidget/generated/GeneratedVergessenWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedloginwidget/generated/GeneratedRectangle_TitelWidget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedloginwidget/generated/GeneratedMerkenWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedloginwidget/generated/GeneratedPasswortWidget1.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedloginwidget/generated/GeneratedLogon_Button_LoginWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedloginwidget/generated/GeneratedTitelWidget.dart';
import 'package:flutterapp/fahrtenbuch_smartapp/generatedloginwidget/generated/GeneratedEMailWidget2.dart';

/* Frame Login
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 640.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 58, 159, 165),
                ),
              ),
              Positioned(
                left: 71.0,
                top: 88.0,
                right: null,
                bottom: null,
                width: 225.0,
                height: 225.0,
                child: GeneratedRectangle_TitelWidget1(),
              ),
              Positioned(
                left: 68.0,
                top: 97.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 167.0,
                child: GeneratedTitelWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 348.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 71.0,
                child: GeneratedEMailWidget2(),
              ),
              Positioned(
                left: 16.0,
                top: 429.0,
                right: null,
                bottom: null,
                width: 328.0,
                height: 62.0,
                child: GeneratedPasswortWidget1(),
              ),
              Positioned(
                left: 16.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 146.0,
                height: 26.0,
                child: GeneratedMerkenWidget(),
              ),
              Positioned(
                left: 214.0,
                top: 509.0,
                right: null,
                bottom: null,
                width: 130.0,
                height: 26.0,
                child: GeneratedVergessenWidget(),
              ),
              Positioned(
                left: 103.0,
                top: 564.0,
                right: null,
                bottom: null,
                width: 154.0,
                height: 40.0,
                child: GeneratedLogon_Button_LoginWidget(),
              )
            ]),
      ),
    ));
  }
}
